# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosTrilinosCouplings(TrilinosBaseClass):
    """Trilinos TrilinosCouplings package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-belos")
    depends_on_trilinos_package("trilinos-muelu")
    depends_on_trilinos_package("trilinos-nox")
    depends_on_trilinos_package("trilinos-stokhos")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-zoltan")
    depends_on_trilinos_package("trilinos-zoltan2core")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_TrilinosCouplings", True),
        ]
        return args
