# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosTrilinoscouplings(TrilinosBaseClass):
    """Trilinos TrilinosCouplings package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-belos")
    depends_on_trilinos_package("trilinos-muelu")
    depends_on_trilinos_package("trilinos-nox")
    depends_on_trilinos_package("trilinos-stokhos")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-zoltan")
    depends_on_trilinos_package("trilinos-zoltan2 +zoltan2core")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_TrilinosCouplings", True))


        args.append(self.define("TRILINOS_TPL_ENABLE_Belos", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_MueLu", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_NOX", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Stokhos", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan2Core", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan2", True))

        return args
