# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosZoltan2(TrilinosBaseClass):
    """Trilinos Zoltan2 package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Subpackage variants
    variant("zoltan2core", default=True, description="Enable the Zoltan2Core subpackage")
    variant("zoltan2sphynx", default=True, description="Enable the Zoltan2Sphynx subpackage")

    # Optional TPL variants
    variant("metis", default=True, description="Enable metis support")
    variant("patoh", default=True, description="Enable patoh support")
    variant("parmetis", default=True, description="Enable parmetis support")
    variant("pulp", default=True, description="Enable py-pulp support")
    variant("scotch", default=True, description="Enable scotch support")
    variant("amd", default=True, description="Enable suite-sparse support")


    # Required package dependencies
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-teuchos +teuchoscore +teuchoscomm +teuchosparameterlist")
    depends_on_trilinos_package("trilinos-xpetra")
    depends_on_trilinos_package("trilinos-zoltan")
    depends_on_trilinos_package("trilinos-anasazi")
    depends_on_trilinos_package("trilinos-belos")
    depends_on_trilinos_package("trilinos-ifpack2")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-muelu", when="+zoltan2sphynx")
    depends_on_trilinos_package("trilinos-galeri", when="+zoltan2sphynx")

    # Optional external (TPL) dependencies
    depends_on("metis", when="+metis")
    depends_on("patoh", when="+patoh")
    depends_on("parmetis", when="+parmetis")
    depends_on("py-pulp", when="+pulp")
    depends_on("scotch", when="+scotch")
    depends_on("suite-sparse", when="+amd")

    # TPL conflicts: subpackages that require an optional TPL
    conflicts("~metis", when="+zoltan2core")
    conflicts("~patoh", when="+zoltan2core")
    conflicts("~parmetis", when="+zoltan2core")
    conflicts("~pulp", when="+zoltan2core")
    conflicts("~scotch", when="+zoltan2core")
    conflicts("~amd", when="+zoltan2core")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Zoltan2", True))

        if self.spec.satisfies("+zoltan2core"):
            args.append(self.define("Trilinos_ENABLE_Zoltan2Core", True))

        if self.spec.satisfies("+zoltan2sphynx"):
            args.append(self.define("Trilinos_ENABLE_Zoltan2Sphynx", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosCore", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosComm", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosParameterList", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Xpetra", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Anasazi", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Belos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Ifpack2", True))

        if self.spec.satisfies("+zoltan2sphynx"):
            args.append(self.define("TRILINOS_TPL_ENABLE_MueLu", True))

        if self.spec.satisfies("+zoltan2sphynx"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Galeri", True))

        if self.spec.satisfies("+metis"):
            args.append(self.define("TRILINOS_TPL_ENABLE_METIS", True))

        if self.spec.satisfies("+patoh"):
            args.append(self.define("TRILINOS_TPL_ENABLE_PaToH", True))

        if self.spec.satisfies("+parmetis"):
            args.append(self.define("TRILINOS_TPL_ENABLE_ParMETIS", True))

        if self.spec.satisfies("+pulp"):
            args.append(self.define("TRILINOS_TPL_ENABLE_PuLP", True))

        if self.spec.satisfies("+scotch"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Scotch", True))

        if self.spec.satisfies("+amd"):
            args.append(self.define("TRILINOS_TPL_ENABLE_AMD", True))

        return args
