# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosZoltan2(TrilinosBaseClass):
    """Trilinos Zoltan2 package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-zoltan2core")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-zoltan2sphynx")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Zoltan2", True))

        args.append(self.define("Trilinos_ENABLE_Zoltan2Core", True))
        args.append(self.define("TPL_ENABLE_Zoltan2Core", True))

        args.append(self.define("Trilinos_ENABLE_Zoltan2Sphynx", True))
        args.append(self.define("TPL_ENABLE_Zoltan2Sphynx", True))

        return args
