# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosZoltan2(TrilinosBaseClass):
    """Trilinos Zoltan2 package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-zoltan2core")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-zoltan2sphynx")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Zoltan2", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan2Core", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan2Sphynx", True))

        return args
