# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosAnasazi(TrilinosBaseClass):
    """Trilinos Anasazi package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("mpi", default=True, description="Enable mpi support")
    variant("tbb", default=True, description="Enable intel-tbb support")

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-thyra +thyracore")
    depends_on_trilinos_package("trilinos-belos")

    # Optional external (TPL) dependencies
    depends_on("mpi", when="+mpi")
    depends_on("intel-tbb", when="+tbb")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Anasazi", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ThyraCore", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Thyra", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Belos", True))

        if self.spec.satisfies("+mpi"):
            args.append(self.define("TRILINOS_TPL_ENABLE_MPI", True))

        if self.spec.satisfies("+tbb"):
            args.append(self.define("TRILINOS_TPL_ENABLE_TBB", True))

        return args
