# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosAnasazi(TrilinosBaseClass):
    """Trilinos Anasazi package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-thyracore")
    depends_on_trilinos_package("trilinos-thyra")
    depends_on_trilinos_package("trilinos-belos")

    # Optional external (TPL) dependencies
    depends_on("mpi")
    depends_on("intel-tbb")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Anasazi", True),
        ]
        return args
