# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosPhalanx(TrilinosBaseClass):
    """Trilinos Phalanx package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchoscore")
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-teuchosparameterlist")
    depends_on_trilinos_package("trilinos-teuchoscomm")
    depends_on("kokkos")
    depends_on_trilinos_package("trilinos-sacado")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Phalanx", True),
        ]
        return args
