# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosSacado(TrilinosBaseClass):
    """Trilinos Sacado package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional package dependencies
    depends_on("kokkos")
    depends_on_trilinos_package("trilinos-teuchoscore")
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-teuchosnumerics")
    depends_on_trilinos_package("trilinos-teuchoscomm")
    depends_on_trilinos_package("trilinos-teuchoskokkoscomm")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Sacado", True),
        ]
        return args
