# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosCompadre(TrilinosBaseClass):
    """Trilinos Compadre package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on("kokkos")
    depends_on("kokkos-kernels")

    # Optional external (TPL) dependencies
    depends_on("mpi", when="+mpi")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Compadre", True))

        args.append(self.define("Trilinos_ENABLE_Kokkos", True))
        args.append(self.define("TPL_ENABLE_Kokkos", True))
        args.append(self.define("Trilinos_ENABLE_KokkosKernels", True))
        args.append(self.define("TPL_ENABLE_KokkosKernels", True))

        if self.spec.satisfies("+mpi"):
            args.append(self.define("TPL_ENABLE_MPI", True))

        return args
