# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosCompadre(TrilinosBaseClass):
    """Trilinos Compadre package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("mpi", default=True, description="Enable mpi support")
    variant("cuda", default=True, description="Enable cuda support")

    # Required package dependencies
    depends_on("kokkos")
    depends_on("kokkos-kernels")

    # Optional external (TPL) dependencies
    depends_on("mpi", when="+mpi")
    depends_on("cuda", when="+cuda")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Compadre", True))


        if self.spec.satisfies("+mpi"):
            args.append(self.define("TRILINOS_TPL_ENABLE_MPI", True))

        if self.spec.satisfies("+cuda"):
            args.append(self.define("TRILINOS_TPL_ENABLE_CUDA", True))

        return args
