# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosAdelus(TrilinosBaseClass):
    """Trilinos Adelus package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on("kokkos")
    depends_on("kokkos-kernels")

    # Required external (TPL) dependencies
    depends_on("blas")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Adelus", True),
        ]
        return args
