# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosPercept(TrilinosBaseClass):
    """Trilinos Percept package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-anasazi")
    depends_on("kokkos")
    depends_on_trilinos_package("trilinos-intrepid2")
    depends_on_trilinos_package("trilinos-shards")
    depends_on("seacas")
    depends_on_trilinos_package("trilinos-stk +stkutil +stkio +stkmesh +stkexpreval +stksearch +stktransfer +stktopology")
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-zoltan")

    # Optional external (TPL) dependencies

    # BEGIN MANUAL SECTION
    # END MANUAL SECTION

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Percept", True))

        args.append(self.define("TPL_ENABLE_Anasazi", True))
        args.append(self.define("TPL_ENABLE_Kokkos", True))
        args.append(self.define("TPL_ENABLE_Intrepid2", True))
        args.append(self.define("TPL_ENABLE_Shards", True))
        args.append(self.define("TPL_ENABLE_SEACASIoss", True))
        args.append(self.define("TPL_ENABLE_SEACAS", True))
        args.append(self.define("TPL_ENABLE_STKUtil", True))
        args.append(self.define("TPL_ENABLE_STK", True))
        args.append(self.define("TPL_ENABLE_STKIO", True))
        args.append(self.define("TPL_ENABLE_STKMesh", True))
        args.append(self.define("TPL_ENABLE_STKExprEval", True))
        args.append(self.define("TPL_ENABLE_STKSearch", True))
        args.append(self.define("TPL_ENABLE_STKTransfer", True))
        args.append(self.define("TPL_ENABLE_STKTopology", True))
        args.append(self.define("TPL_ENABLE_Teuchos", True))
        args.append(self.define("TPL_ENABLE_Zoltan", True))


    # BEGIN MANUAL CMAKE ARGS
    # END MANUAL CMAKE ARGS

        return args
