# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosPercept(TrilinosBaseClass):
    """Trilinos Percept package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-intrepid2")
    depends_on_trilinos_package("trilinos-seacasioss")
    depends_on("seacas")
    depends_on_trilinos_package("trilinos-stkutil")
    depends_on("stk")
    depends_on_trilinos_package("trilinos-stkio")
    depends_on_trilinos_package("trilinos-stkmesh")
    depends_on_trilinos_package("trilinos-stkexpreval")
    depends_on_trilinos_package("trilinos-stksearch")
    depends_on_trilinos_package("trilinos-stktransfer")
    depends_on_trilinos_package("trilinos-zoltan")

    # Optional external (TPL) dependencies

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Percept", True),
        ]
        return args
