# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosPercept(TrilinosBaseClass):
    """Trilinos Percept package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("opennurbs", default=True, description="Enable opennurbs support")


    # Required package dependencies
    depends_on_trilinos_package("trilinos-intrepid2")
    depends_on("seacas")
    depends_on("stk")
    depends_on_trilinos_package("trilinos-zoltan")

    # Optional external (TPL) dependencies
    depends_on("opennurbs", when="+opennurbs")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Percept", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Intrepid2", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan", True))

        if self.spec.satisfies("+opennurbs"):
            args.append(self.define("TRILINOS_TPL_ENABLE_OpenNURBS", True))

        return args
