# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosTpetra(TrilinosBaseClass):
    """Trilinos Tpetra package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Subpackage variants
    variant("tpetratsqr", default=True, description="Enable the TpetraTSQR subpackage")
    variant("tpetracore", default=True, description="Enable the TpetraCore subpackage")

    # Optional TPL variants
    variant("cublas", default=True, description="Enable cuda support")
    variant("cusolver", default=True, description="Enable cuda support")
    variant("mpi-advance", default=True, description="Enable mpi-advance support")


    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos +teuchoskokkoscompat +teuchoskokkoscomm")
    depends_on("kokkos")
    depends_on("kokkos-kernels")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-teuchos +teuchosnumerics", when="+tpetracore")

    # Optional external (TPL) dependencies
    depends_on("cuda", when="+cublas")
    depends_on("cuda", when="+cusolver")
    depends_on("mpi", when="+mpi")
    depends_on("cuda", when="+cuda")
    depends_on("mpi-advance", when="+mpi-advance")

    # TPL conflicts: subpackages that require an optional TPL
    conflicts("~cublas", when="+tpetratsqr")
    conflicts("~cusolver", when="+tpetratsqr")
    conflicts("~mpi", when="+tpetracore")
    conflicts("~cuda", when="+tpetracore")
    conflicts("~mpi-advance", when="+tpetracore")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Tpetra", True))

        if self.spec.satisfies("+tpetratsqr"):
            args.append(self.define("Trilinos_ENABLE_TpetraTSQR", True))

        if self.spec.satisfies("+tpetracore"):
            args.append(self.define("Trilinos_ENABLE_TpetraCore", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosKokkosCompat", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosKokkosComm", True))

        if self.spec.satisfies("+tpetracore"):
            args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosNumerics", True))

        if self.spec.satisfies("+cublas"):
            args.append(self.define("TRILINOS_TPL_ENABLE_CUBLAS", True))

        if self.spec.satisfies("+cusolver"):
            args.append(self.define("TRILINOS_TPL_ENABLE_CUSOLVER", True))

        if self.spec.satisfies("+mpi"):
            args.append(self.define("TRILINOS_TPL_ENABLE_MPI", True))

        if self.spec.satisfies("+cuda"):
            args.append(self.define("TRILINOS_TPL_ENABLE_CUDA", True))

        if self.spec.satisfies("+mpi-advance"):
            args.append(self.define("TRILINOS_TPL_ENABLE_mpi_advance", True))

        return args
