# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosTpetra(TrilinosBaseClass):
    """Trilinos Tpetra package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Subpackage variants
    variant("tpetratsqr", default=True, description="Enable the TpetraTSQR subpackage")
    variant("tpetracore", default=True, description="Enable the TpetraCore subpackage")

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on("kokkos")
    depends_on("kokkos-kernels")
    depends_on_trilinos_package("trilinos-teuchoskokkoscompat")
    depends_on_trilinos_package("trilinos-teuchoskokkoscomm")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-teuchosnumerics", when="+tpetracore")

    # Optional external (TPL) dependencies
    depends_on("mpi", when="+tpetracore")
    depends_on("cuda", when="+tpetracore")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Tpetra", True),
        ]
        return args
