# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosZoltan2Core(TrilinosBaseClass):
    """Trilinos Zoltan2Core package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("metis", default=True, description="Enable metis support")
    variant("patoh", default=True, description="Enable patoh support")
    variant("parmetis", default=True, description="Enable parmetis support")
    variant("pulp", default=True, description="Enable py-pulp support")
    variant("scotch", default=True, description="Enable scotch support")
    variant("amd", default=True, description="Enable suite-sparse support")

    # Required package dependencies
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-teuchos +teuchoscore +teuchoscomm +teuchosparameterlist")
    depends_on_trilinos_package("trilinos-xpetra")
    depends_on_trilinos_package("trilinos-zoltan")

    # Optional external (TPL) dependencies
    depends_on("metis", when="+metis")
    depends_on("patoh", when="+patoh")
    depends_on("parmetis", when="+parmetis")
    depends_on("py-pulp", when="+pulp")
    depends_on("scotch", when="+scotch")
    depends_on("suite-sparse", when="+amd")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Zoltan2Core", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosCore", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosComm", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosParameterList", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Xpetra", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan", True))

        if self.spec.satisfies("+metis"):
            args.append(self.define("TRILINOS_TPL_ENABLE_METIS", True))

        if self.spec.satisfies("+patoh"):
            args.append(self.define("TRILINOS_TPL_ENABLE_PaToH", True))

        if self.spec.satisfies("+parmetis"):
            args.append(self.define("TRILINOS_TPL_ENABLE_ParMETIS", True))

        if self.spec.satisfies("+pulp"):
            args.append(self.define("TRILINOS_TPL_ENABLE_PuLP", True))

        if self.spec.satisfies("+scotch"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Scotch", True))

        if self.spec.satisfies("+amd"):
            args.append(self.define("TRILINOS_TPL_ENABLE_AMD", True))

        return args
