# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosZoltan2Core(TrilinosBaseClass):
    """Trilinos Zoltan2Core package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-teuchoscore")
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-teuchoscomm")
    depends_on_trilinos_package("trilinos-teuchosparameterlist")
    depends_on_trilinos_package("trilinos-xpetra")
    depends_on_trilinos_package("trilinos-zoltan")

    # Optional external (TPL) dependencies
    depends_on("metis")
    depends_on("parmetis")
    depends_on("scotch")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Zoltan2Core", True),
        ]
        return args
