# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosZoltan2core(TrilinosBaseClass):
    """Trilinos Zoltan2Core package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("metis", default=True, description="Enable metis support")
    variant("parmetis", default=True, description="Enable parmetis support")
    variant("scotch", default=True, description="Enable scotch support")


    # Required package dependencies
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-teuchos +teuchoscore +teuchoscomm +teuchosparameterlist")
    depends_on_trilinos_package("trilinos-xpetra")
    depends_on_trilinos_package("trilinos-zoltan")

    # Optional external (TPL) dependencies
    depends_on("metis", when="+metis")
    depends_on("parmetis", when="+parmetis")
    depends_on("scotch", when="+scotch")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Zoltan2Core", True))

        args.append(self.define("Trilinos_ENABLE_Tpetra", True))
        args.append(self.define("TPL_ENABLE_Tpetra", True))
        args.append(self.define("Trilinos_ENABLE_TeuchosCore", True))
        args.append(self.define("TPL_ENABLE_TeuchosCore", True))
        args.append(self.define("Trilinos_ENABLE_Teuchos", True))
        args.append(self.define("TPL_ENABLE_Teuchos", True))
        args.append(self.define("Trilinos_ENABLE_TeuchosComm", True))
        args.append(self.define("TPL_ENABLE_TeuchosComm", True))
        args.append(self.define("Trilinos_ENABLE_TeuchosParameterList", True))
        args.append(self.define("TPL_ENABLE_TeuchosParameterList", True))
        args.append(self.define("Trilinos_ENABLE_Xpetra", True))
        args.append(self.define("TPL_ENABLE_Xpetra", True))
        args.append(self.define("Trilinos_ENABLE_Zoltan", True))
        args.append(self.define("TPL_ENABLE_Zoltan", True))

        if self.spec.satisfies("+metis"):
            args.append(self.define("TPL_ENABLE_METIS", True))

        if self.spec.satisfies("+parmetis"):
            args.append(self.define("TPL_ENABLE_ParMETIS", True))

        if self.spec.satisfies("+scotch"):
            args.append(self.define("TPL_ENABLE_Scotch", True))

        return args
