# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosThyra(TrilinosBaseClass):
    """Trilinos Thyra package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Subpackage variants
    variant("thyracore", default=True, description="Enable the ThyraCore subpackage")
    variant("thyratpetraadapters", default=True, description="Enable the ThyraTpetraAdapters subpackage")

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchoscore")
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-teuchosparameterlist")
    depends_on_trilinos_package("trilinos-teuchoscomm")
    depends_on_trilinos_package("trilinos-teuchosnumerics")
    depends_on_trilinos_package("trilinos-rtop")
    depends_on_trilinos_package("trilinos-tpetra")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Thyra", True),
        ]
        return args
