# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosThyra(TrilinosBaseClass):
    """Trilinos Thyra package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Subpackage variants
    variant("thyracore", default=True, description="Enable the ThyraCore subpackage")
    variant("thyratpetraadapters", default=True, description="Enable the ThyraTpetraAdapters subpackage")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-teuchos +teuchoscore +teuchosparameterlist +teuchoscomm +teuchosnumerics", when="+thyracore")
    depends_on_trilinos_package("trilinos-rtop", when="+thyracore")
    depends_on_trilinos_package("trilinos-tpetra", when="+thyratpetraadapters")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Thyra", True))

        if self.spec.satisfies("+thyracore"):
            args.append(self.define("Trilinos_ENABLE_ThyraCore", True))

        if self.spec.satisfies("+thyratpetraadapters"):
            args.append(self.define("Trilinos_ENABLE_ThyraTpetraAdapters", True))


        if self.spec.satisfies("+thyracore"):
            args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosCore", True))

        if self.spec.satisfies("+thyracore"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))

        if self.spec.satisfies("+thyracore"):
            args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosParameterList", True))

        if self.spec.satisfies("+thyracore"):
            args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosComm", True))

        if self.spec.satisfies("+thyracore"):
            args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosNumerics", True))

        if self.spec.satisfies("+thyracore"):
            args.append(self.define("TRILINOS_TPL_ENABLE_RTOp", True))

        if self.spec.satisfies("+thyratpetraadapters"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))

        return args
