# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosIntrepid2(TrilinosBaseClass):
    """Trilinos Intrepid2 package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchoscore")
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-teuchosnumerics")
    depends_on_trilinos_package("trilinos-shards")
    depends_on("kokkos")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-sacado")
    depends_on("kokkos-kernels")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Intrepid2", True),
        ]
        return args
