# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class Trilinosmagistrate(TrilinosBaseClass):
    """Trilinos magistrate package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional package dependencies
    depends_on("kokkos")
    depends_on("kokkos-kernels")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_magistrate", True))


        return args
