# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosMagistrate(TrilinosBaseClass):
    """Trilinos magistrate package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional package dependencies
    depends_on("kokkos")
    depends_on("kokkos-kernels")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_magistrate", True))


        return args
