# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosTrilinosInstallTests(TrilinosBaseClass):
    """Trilinos TrilinosInstallTests package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_TrilinosInstallTests", True))


        return args
