# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosRTOp(TrilinosBaseClass):
    """Trilinos RTOp package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchoscore")
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-teuchoscomm")
    depends_on_trilinos_package("trilinos-teuchosnumerics")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_RTOp", True),
        ]
        return args
