# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosKrino(TrilinosBaseClass):
    """Trilinos Krino package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-seacasioss")
    depends_on("seacas")
    depends_on_trilinos_package("trilinos-seacasexodus")
    depends_on_trilinos_package("trilinos-stkbalance")
    depends_on("stk")
    depends_on_trilinos_package("trilinos-stkexpreval")
    depends_on_trilinos_package("trilinos-stkmath")
    depends_on_trilinos_package("trilinos-stkio")
    depends_on_trilinos_package("trilinos-stksearch")
    depends_on_trilinos_package("trilinos-stktopology")
    depends_on_trilinos_package("trilinos-stkutil")
    depends_on_trilinos_package("trilinos-stktools")
    depends_on_trilinos_package("trilinos-stkemend")
    depends_on_trilinos_package("trilinos-intrepid2")
    depends_on_trilinos_package("trilinos-sacado")

    # Required external (TPL) dependencies
    depends_on("boost")

    # Optional external (TPL) dependencies
    depends_on("mpi")
    depends_on("parmetis")
    depends_on("yaml-cpp")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Krino", True),
        ]
        return args
