# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosKrino(TrilinosBaseClass):
    """Trilinos Krino package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("parmetis", default=True, description="Enable parmetis support")
    variant("yamlcpp", default=True, description="Enable yaml-cpp support")


    # Required package dependencies
    depends_on("seacas")
    depends_on("stk")
    depends_on_trilinos_package("trilinos-intrepid2")
    depends_on_trilinos_package("trilinos-sacado")

    # Required external (TPL) dependencies
    depends_on("boost")

    # Optional external (TPL) dependencies
    depends_on("mpi", when="+mpi")
    depends_on("parmetis", when="+parmetis")
    depends_on("yaml-cpp", when="+yamlcpp")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Krino", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Intrepid2", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Sacado", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Boost", True))

        if self.spec.satisfies("+mpi"):
            args.append(self.define("TRILINOS_TPL_ENABLE_MPI", True))

        if self.spec.satisfies("+parmetis"):
            args.append(self.define("TRILINOS_TPL_ENABLE_ParMETIS", True))

        if self.spec.satisfies("+yamlcpp"):
            args.append(self.define("TRILINOS_TPL_ENABLE_yamlcpp", True))

        return args
