# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosKrino(TrilinosBaseClass):
    """Trilinos Krino package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("parmetis", default=True, description="Enable parmetis support")


    # Required package dependencies
    depends_on("seacas")
    depends_on_trilinos_package("trilinos-stk +stkbalance +stkexpreval +stkmath +stkio +stksearch +stktopology +stkutil +stktools +stkemend")
    depends_on_trilinos_package("trilinos-intrepid2")
    depends_on_trilinos_package("trilinos-sacado")

    # Required external (TPL) dependencies
    depends_on("boost")

    # Optional external (TPL) dependencies
    depends_on("mpi", when="+mpi")
    depends_on("parmetis", when="+parmetis")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Krino", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_STKBalance", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_STK", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_STKExprEval", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_STKMath", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_STKIO", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_STKSearch", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_STKTopology", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_STKUtil", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_STKTools", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_STKEmend", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Intrepid2", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Sacado", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Boost", True))

        if self.spec.satisfies("+mpi"):
            args.append(self.define("TRILINOS_TPL_ENABLE_MPI", True))
            #by hand
            args.append(self.define("TPL_ENABLE_MPI", True))

        if self.spec.satisfies("+parmetis"):
            args.append(self.define("TRILINOS_TPL_ENABLE_ParMETIS", True))

        return args
