# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosMuelu(TrilinosBaseClass):
    """Trilinos MueLu package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("boost", default=True, description="Enable boost support")
    variant("amgx", default=True, description="Enable amgx support")
    variant("viennacl", default=True, description="Enable viennacl support")
    variant("mkl", default=True, description="Enable intel-oneapi-mkl support")
    variant("cusparse", default=True, description="Enable cuda support")
    variant("mlpack", default=True, description="Enable mlpack support")


    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-xpetra")
    depends_on("kokkos")
    depends_on("kokkos-kernels")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-amesos2")
    depends_on_trilinos_package("trilinos-belos")
    depends_on_trilinos_package("trilinos-teko")
    depends_on_trilinos_package("trilinos-ifpack2")
    depends_on_trilinos_package("trilinos-intrepid2")
    depends_on_trilinos_package("trilinos-zoltan")
    depends_on_trilinos_package("trilinos-zoltan2 +zoltan2core")
    depends_on_trilinos_package("trilinos-stratimikos")
    depends_on_trilinos_package("trilinos-thyra +thyratpetraadapters")

    # Required external (TPL) dependencies
    depends_on("blas")
    depends_on("lapack")

    # Optional external (TPL) dependencies
    depends_on("boost", when="+boost")
    depends_on("amgx", when="+amgx")
    depends_on("viennacl", when="+viennacl")
    depends_on("intel-oneapi-mkl", when="+mkl")
    depends_on("cuda", when="+cusparse")
    depends_on("mlpack", when="+mlpack")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_MueLu", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Xpetra", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_BLAS", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_LAPACK", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Amesos2", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Belos", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Teko", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Ifpack2", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Intrepid2", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan2Core", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan2", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Stratimikos", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Thyra", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ThyraTpetraAdapters", True))

        if self.spec.satisfies("+boost"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Boost", True))

        if self.spec.satisfies("+amgx"):
            args.append(self.define("TRILINOS_TPL_ENABLE_AmgX", True))

        if self.spec.satisfies("+viennacl"):
            args.append(self.define("TRILINOS_TPL_ENABLE_ViennaCL", True))

        if self.spec.satisfies("+mkl"):
            args.append(self.define("TRILINOS_TPL_ENABLE_MKL", True))

        if self.spec.satisfies("+cusparse"):
            args.append(self.define("TRILINOS_TPL_ENABLE_CUSPARSE", True))

        if self.spec.satisfies("+mlpack"):
            args.append(self.define("TRILINOS_TPL_ENABLE_mlpack", True))

        return args
