# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosMueLu(TrilinosBaseClass):
    """Trilinos MueLu package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-xpetra")
    depends_on("kokkos")
    depends_on("kokkos-kernels")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-amesos2")
    depends_on_trilinos_package("trilinos-belos")
    depends_on_trilinos_package("trilinos-teko")
    depends_on_trilinos_package("trilinos-ifpack2")
    depends_on_trilinos_package("trilinos-intrepid2")
    depends_on_trilinos_package("trilinos-zoltan")
    depends_on_trilinos_package("trilinos-zoltan2core")
    depends_on_trilinos_package("trilinos-stratimikos")
    depends_on_trilinos_package("trilinos-thyra")
    depends_on_trilinos_package("trilinos-thyratpetraadapters")

    # Required external (TPL) dependencies
    depends_on("blas")
    depends_on("lapack")

    # Optional external (TPL) dependencies
    depends_on("boost")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_MueLu", True),
        ]
        return args
