# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosPiro(TrilinosBaseClass):
    """Trilinos Piro package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-stratimikos")
    depends_on_trilinos_package("trilinos-thyra +thyracore")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-teko")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-nox")
    depends_on_trilinos_package("trilinos-tempus")
    depends_on_trilinos_package("trilinos-rol")
    depends_on_trilinos_package("trilinos-ifpack2")
    depends_on_trilinos_package("trilinos-muelu")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Piro", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Stratimikos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_ThyraCore", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Thyra", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Teko", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_NOX", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Tempus", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ROL", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Ifpack2", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_MueLu", True))

        return args
