# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosShyLU(TrilinosBaseClass):
    """Trilinos ShyLU package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-shylu_dd")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-shylu_node")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_ShyLU", True),
        ]
        return args
