# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosShylu(TrilinosBaseClass):
    """Trilinos ShyLU package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-shylu-dd")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-shylu-node")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_ShyLU", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ShyLU_DD", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ShyLU_Node", True))

        return args
