# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosStk(TrilinosBaseClass):
    """Trilinos STK package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Subpackage variants
    variant("stkutil", default=True, description="Enable the STKUtil subpackage")
    variant("stkemend", default=True, description="Enable the STKEmend subpackage")
    variant("stkcoupling", default=True, description="Enable the STKCoupling subpackage")
    variant("stkmath", default=True, description="Enable the STKMath subpackage")
    variant("stksimd", default=True, description="Enable the STKSimd subpackage")
    variant("stkngp-test", default=True, description="Enable the STKNGP_TEST subpackage")
    variant("stkexpreval", default=True, description="Enable the STKExprEval subpackage")
    variant("stktopology", default=True, description="Enable the STKTopology subpackage")
    variant("stksearch", default=True, description="Enable the STKSearch subpackage")
    variant("stkmiddle-mesh", default=True, description="Enable the STKMiddle_mesh subpackage")
    variant("stktransfer", default=True, description="Enable the STKTransfer subpackage")
    variant("stkmesh", default=True, description="Enable the STKMesh subpackage")
    variant("stkio", default=True, description="Enable the STKIO subpackage")
    variant("stksearchutil", default=True, description="Enable the STKSearchUtil subpackage")
    variant("stktransferutil", default=True, description="Enable the STKTransferUtil subpackage")
    variant("stkmiddle-mesh-util", default=True, description="Enable the STKMiddle_mesh_util subpackage")
    variant("stktools", default=True, description="Enable the STKTools subpackage")
    variant("stkbalance", default=True, description="Enable the STKBalance subpackage")
    variant("stkunit-test-utils", default=True, description="Enable the STKUnit_test_utils subpackage")
    variant("stkunit-tests", default=True, description="Enable the STKUnit_tests subpackage")
    variant("stkdoc-tests", default=True, description="Enable the STKDoc_tests subpackage")
    variant("stkintegration-tests", default=True, description="Enable the STKIntegration_tests subpackage")
    variant("stkperformance-tests", default=True, description="Enable the STKPerformance_tests subpackage")

    # Optional TPL variants
    variant("boost", default=True, description="Enable boost support")


    # Required package dependencies
    depends_on("kokkos")
    depends_on_trilinos_package("trilinos-shards")
    depends_on("seacas")
    depends_on_trilinos_package("trilinos-teuchos +teuchoscore +teuchosparameterlist")
    depends_on_trilinos_package("trilinos-zoltan2 +zoltan2core")

    # Optional package dependencies
    depends_on("seacas", when="+stkutil")
    depends_on_trilinos_package("trilinos-intrepid2", when="+stksearchutil")

    # Required external (TPL) dependencies
    depends_on("mpi")
    depends_on("googletest")
    depends_on("lapack")
    depends_on("blas")

    # Optional external (TPL) dependencies
    depends_on("boost", when="+boost")

    # TPL conflicts: subpackages that require an optional TPL
    conflicts("~boost", when="+stkutil")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_STK", True))

        if self.spec.satisfies("+stkutil"):
            args.append(self.define("Trilinos_ENABLE_STKUtil", True))

        if self.spec.satisfies("+stkemend"):
            args.append(self.define("Trilinos_ENABLE_STKEmend", True))

        if self.spec.satisfies("+stkcoupling"):
            args.append(self.define("Trilinos_ENABLE_STKCoupling", True))

        if self.spec.satisfies("+stkmath"):
            args.append(self.define("Trilinos_ENABLE_STKMath", True))

        if self.spec.satisfies("+stksimd"):
            args.append(self.define("Trilinos_ENABLE_STKSimd", True))

        if self.spec.satisfies("+stkngp-test"):
            args.append(self.define("Trilinos_ENABLE_STKNGP_TEST", True))

        if self.spec.satisfies("+stkexpreval"):
            args.append(self.define("Trilinos_ENABLE_STKExprEval", True))

        if self.spec.satisfies("+stktopology"):
            args.append(self.define("Trilinos_ENABLE_STKTopology", True))

        if self.spec.satisfies("+stksearch"):
            args.append(self.define("Trilinos_ENABLE_STKSearch", True))

        if self.spec.satisfies("+stkmiddle-mesh"):
            args.append(self.define("Trilinos_ENABLE_STKMiddle_mesh", True))

        if self.spec.satisfies("+stktransfer"):
            args.append(self.define("Trilinos_ENABLE_STKTransfer", True))

        if self.spec.satisfies("+stkmesh"):
            args.append(self.define("Trilinos_ENABLE_STKMesh", True))

        if self.spec.satisfies("+stkio"):
            args.append(self.define("Trilinos_ENABLE_STKIO", True))

        if self.spec.satisfies("+stksearchutil"):
            args.append(self.define("Trilinos_ENABLE_STKSearchUtil", True))

        if self.spec.satisfies("+stktransferutil"):
            args.append(self.define("Trilinos_ENABLE_STKTransferUtil", True))

        if self.spec.satisfies("+stkmiddle-mesh-util"):
            args.append(self.define("Trilinos_ENABLE_STKMiddle_mesh_util", True))

        if self.spec.satisfies("+stktools"):
            args.append(self.define("Trilinos_ENABLE_STKTools", True))

        if self.spec.satisfies("+stkbalance"):
            args.append(self.define("Trilinos_ENABLE_STKBalance", True))

        if self.spec.satisfies("+stkunit-test-utils"):
            args.append(self.define("Trilinos_ENABLE_STKUnit_test_utils", True))

        if self.spec.satisfies("+stkunit-tests"):
            args.append(self.define("Trilinos_ENABLE_STKUnit_tests", True))

        if self.spec.satisfies("+stkdoc-tests"):
            args.append(self.define("Trilinos_ENABLE_STKDoc_tests", True))

        if self.spec.satisfies("+stkintegration-tests"):
            args.append(self.define("Trilinos_ENABLE_STKIntegration_tests", True))

        if self.spec.satisfies("+stkperformance-tests"):
            args.append(self.define("Trilinos_ENABLE_STKPerformance_tests", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Shards", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosCore", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosParameterList", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan2Core", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan2", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_MPI", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_gtest", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_LAPACK", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_BLAS", True))

        if self.spec.satisfies("+stksearchutil"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Intrepid2", True))

        if self.spec.satisfies("+boost"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Boost", True))

        return args
