# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class STK(CMakePackage):
    """Trilinos STK package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    homepage = "https://trilinos.github.io"
    url = (
        "https://github.com/trilinos/Trilinos/archive/"
        "trilinos-release-{0}.tar.gz"
    )
    git = "https://github.com/trilinos/Trilinos.git"

    version("16.4.0", sha256="placeholder_sha256_16_4_0", url="https://github.com/trilinos/Trilinos/archive/trilinos-release-16-4-0.tar.gz")
    version("16.0.0", sha256="placeholder_sha256_16_0_0", url="https://github.com/trilinos/Trilinos/archive/trilinos-release-16-0-0.tar.gz")
    version("15.1.1", sha256="placeholder_sha256_15_1_1", url="https://github.com/trilinos/Trilinos/archive/trilinos-release-15-1-1.tar.gz")
    version("14.4.0", sha256="placeholder_sha256_14_4_0", url="https://github.com/trilinos/Trilinos/archive/trilinos-release-14-4-0.tar.gz")
    version("develop", branch="develop")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_STK", True),
        ]
        return args
