# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosTeuchos(TrilinosBaseClass):
    """Trilinos Teuchos package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Subpackage variants
    variant("teuchoscore", default=True, description="Enable the TeuchosCore subpackage")
    variant("teuchosparser", default=True, description="Enable the TeuchosParser subpackage")
    variant("teuchosparameterlist", default=True, description="Enable the TeuchosParameterList subpackage")
    variant("teuchoscomm", default=True, description="Enable the TeuchosComm subpackage")
    variant("teuchosnumerics", default=True, description="Enable the TeuchosNumerics subpackage")
    variant("teuchosremainder", default=True, description="Enable the TeuchosRemainder subpackage")
    variant("teuchoskokkoscompat", default=True, description="Enable the TeuchosKokkosCompat subpackage")
    variant("teuchoskokkoscomm", default=True, description="Enable the TeuchosKokkosComm subpackage")

    # Required package dependencies
    depends_on("kokkos")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-magistrate", when="+teuchoscomm")

    # Required external (TPL) dependencies
    depends_on("blas")
    depends_on("lapack")

    # Optional external (TPL) dependencies
    depends_on("boost", when="+teuchoscore")
    depends_on("mpi", when="+teuchoscore")
    depends_on("mpi", when="+teuchoskokkoscomm")
    depends_on("yaml-cpp", when="+teuchosparameterlist")
    depends_on("eigen", when="+teuchosnumerics")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Teuchos", True),
        ]
        return args
