# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosPanzer(TrilinosBaseClass):
    """Trilinos Panzer package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Subpackage variants
    variant("panzercore", default=True, description="Enable the PanzerCore subpackage")
    variant("panzerdofmgr", default=True, description="Enable the PanzerDofMgr subpackage")
    variant("panzerdiscfe", default=True, description="Enable the PanzerDiscFE subpackage")
    variant("panzeradaptersstk", default=True, description="Enable the PanzerAdaptersSTK subpackage")
    variant("panzerminiem", default=True, description="Enable the PanzerMiniEM subpackage")
    variant("panzerexpreval", default=True, description="Enable the PanzerExprEval subpackage")

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchoscore")
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-teuchoscomm")
    depends_on_trilinos_package("trilinos-teuchosparameterlist")
    depends_on_trilinos_package("trilinos-tpetracore")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-shards")
    depends_on_trilinos_package("trilinos-intrepid2")
    depends_on_trilinos_package("trilinos-phalanx")
    depends_on("kokkos")
    depends_on_trilinos_package("trilinos-sacado")
    depends_on_trilinos_package("trilinos-thyracore")
    depends_on_trilinos_package("trilinos-thyra")
    depends_on_trilinos_package("trilinos-thyratpetraadapters")
    depends_on_trilinos_package("trilinos-zoltan")
    depends_on_trilinos_package("trilinos-stkutil")
    depends_on("stk")
    depends_on_trilinos_package("trilinos-stktools")
    depends_on_trilinos_package("trilinos-stktopology")
    depends_on_trilinos_package("trilinos-stkmesh")
    depends_on_trilinos_package("trilinos-stkio")
    depends_on_trilinos_package("trilinos-stratimikos")
    depends_on_trilinos_package("trilinos-piro")
    depends_on_trilinos_package("trilinos-nox")
    depends_on_trilinos_package("trilinos-belos")
    depends_on_trilinos_package("trilinos-teko")
    depends_on_trilinos_package("trilinos-muelu")
    depends_on_trilinos_package("trilinos-teuchosparser")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-stksearch", when="+panzeradaptersstk")
    depends_on_trilinos_package("trilinos-seacasioss", when="+panzeradaptersstk")
    depends_on("seacas", when="+panzeradaptersstk")
    depends_on("seacas", when="+panzeradaptersstk")
    depends_on_trilinos_package("trilinos-seacasexodus", when="+panzeradaptersstk")
    depends_on_trilinos_package("trilinos-percept", when="+panzeradaptersstk")
    depends_on_trilinos_package("trilinos-ifpack2", when="+panzeradaptersstk")
    depends_on_trilinos_package("trilinos-tempus", when="+panzeradaptersstk")
    depends_on_trilinos_package("trilinos-shylu_nodetacho", when="+panzerminiem")
    depends_on_trilinos_package("trilinos-shylu_node", when="+panzerminiem")

    # Required external (TPL) dependencies
    depends_on("mpi")

    # Optional external (TPL) dependencies
    depends_on("papi", when="+panzerdiscfe")
    depends_on("papi", when="+panzerminiem")
    depends_on("camal", when="+panzerdiscfe")
    depends_on("camal", when="+panzerminiem")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Panzer", True),
        ]
        return args
