# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosPanzer(TrilinosBaseClass):
    """Trilinos Panzer package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Subpackage variants
    variant("panzercore", default=True, description="Enable the PanzerCore subpackage")
    variant("panzerdofmgr", default=True, description="Enable the PanzerDofMgr subpackage")
    variant("panzerdiscfe", default=True, description="Enable the PanzerDiscFE subpackage")
    variant("panzeradaptersstk", default=True, description="Enable the PanzerAdaptersSTK subpackage")
    variant("panzerminiem", default=True, description="Enable the PanzerMiniEM subpackage")
    variant("panzerexpreval", default=True, description="Enable the PanzerExprEval subpackage")

    # Optional TPL variants
    variant("papi", default=True, description="Enable papi support")
    variant("camal", default=True, description="Enable camal support")


    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos +teuchoscore +teuchoscomm +teuchosparameterlist +teuchosparser")
    depends_on_trilinos_package("trilinos-tpetra +tpetracore")
    depends_on_trilinos_package("trilinos-shards")
    depends_on_trilinos_package("trilinos-intrepid2")
    depends_on_trilinos_package("trilinos-phalanx")
    depends_on("kokkos")
    depends_on_trilinos_package("trilinos-sacado")
    depends_on_trilinos_package("trilinos-thyra +thyracore +thyratpetraadapters")
    depends_on_trilinos_package("trilinos-zoltan")
    depends_on("stk")
    depends_on_trilinos_package("trilinos-stratimikos")
    depends_on_trilinos_package("trilinos-piro")
    depends_on_trilinos_package("trilinos-nox")
    depends_on_trilinos_package("trilinos-belos")
    depends_on_trilinos_package("trilinos-teko")
    depends_on_trilinos_package("trilinos-muelu")

    # Optional package dependencies
    depends_on("stk", when="+panzeradaptersstk")
    depends_on("seacas", when="+panzeradaptersstk")
    depends_on_trilinos_package("trilinos-percept", when="+panzeradaptersstk")
    depends_on_trilinos_package("trilinos-ifpack2", when="+panzeradaptersstk")
    depends_on_trilinos_package("trilinos-tempus", when="+panzeradaptersstk")
    depends_on_trilinos_package("trilinos-shylu-node +shylu-nodetacho", when="+panzerminiem")

    # Required external (TPL) dependencies
    depends_on("mpi")

    # Optional external (TPL) dependencies
    depends_on("papi", when="+papi")
    depends_on("camal", when="+camal")

    # TPL conflicts: subpackages that require an optional TPL
    conflicts("~papi", when="+panzerdiscfe")
    conflicts("~papi", when="+panzerminiem")
    conflicts("~camal", when="+panzerdiscfe")
    conflicts("~camal", when="+panzerminiem")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Panzer", True))

        if self.spec.satisfies("+panzercore"):
            args.append(self.define("Trilinos_ENABLE_PanzerCore", True))

        if self.spec.satisfies("+panzerdofmgr"):
            args.append(self.define("Trilinos_ENABLE_PanzerDofMgr", True))

        if self.spec.satisfies("+panzerdiscfe"):
            args.append(self.define("Trilinos_ENABLE_PanzerDiscFE", True))

        if self.spec.satisfies("+panzeradaptersstk"):
            args.append(self.define("Trilinos_ENABLE_PanzerAdaptersSTK", True))

        if self.spec.satisfies("+panzerminiem"):
            args.append(self.define("Trilinos_ENABLE_PanzerMiniEM", True))

        if self.spec.satisfies("+panzerexpreval"):
            args.append(self.define("Trilinos_ENABLE_PanzerExprEval", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosCore", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosComm", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosParameterList", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TpetraCore", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Shards", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Intrepid2", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Phalanx", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Sacado", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_ThyraCore", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Thyra", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_ThyraTpetraAdapters", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Stratimikos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Piro", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_NOX", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Belos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Teko", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_MueLu", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosParser", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_MPI", True))

        if self.spec.satisfies("+panzeradaptersstk"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Percept", True))

        if self.spec.satisfies("+panzeradaptersstk"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Ifpack2", True))

        if self.spec.satisfies("+panzeradaptersstk"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Tempus", True))

        if self.spec.satisfies("+panzerminiem"):
            args.append(self.define("TRILINOS_TPL_ENABLE_ShyLU_NodeTacho", True))

        if self.spec.satisfies("+panzerminiem"):
            args.append(self.define("TRILINOS_TPL_ENABLE_ShyLU_Node", True))

        if self.spec.satisfies("+papi"):
            args.append(self.define("TRILINOS_TPL_ENABLE_PAPI", True))

        if self.spec.satisfies("+camal"):
            args.append(self.define("TRILINOS_TPL_ENABLE_CAMAL", True))

        return args
