# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosTeko(TrilinosBaseClass):
    """Trilinos Teko package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-thyra")
    depends_on_trilinos_package("trilinos-stratimikos")
    depends_on_trilinos_package("trilinos-anasazi")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-thyratpetraadapters")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-ifpack2")
    depends_on_trilinos_package("trilinos-amesos2")
    depends_on_trilinos_package("trilinos-belos")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Teko", True),
        ]
        return args
