# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosTrilinosSS(TrilinosBaseClass):
    """Trilinos TrilinosSS package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_TrilinosSS", True),
        ]
        return args
