# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosIfpack2(TrilinosBaseClass):
    """Trilinos Ifpack2 package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("hypre", default=True, description="Enable hypre support")
    variant("cholmod", default=True, description="Enable suite-sparse support")
    variant("lemon", default=True, description="Enable lemon support")
    variant("metis", default=True, description="Enable metis support")


    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on("kokkos-kernels")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-xpetra")
    depends_on_trilinos_package("trilinos-zoltan2 +zoltan2core")
    depends_on_trilinos_package("trilinos-thyra +thyratpetraadapters")
    depends_on_trilinos_package("trilinos-amesos2")
    depends_on_trilinos_package("trilinos-shylu-node +shylu-nodebasker +shylu-nodehts +shylu-nodefastilu")

    # Optional external (TPL) dependencies
    depends_on("hypre", when="+hypre")
    depends_on("suite-sparse", when="+cholmod")
    depends_on("lemon", when="+lemon")
    depends_on("metis", when="+metis")
    depends_on("mpi", when="+mpi")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Ifpack2", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Xpetra", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan2Core", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan2", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ThyraTpetraAdapters", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Thyra", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Amesos2", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ShyLU_NodeBasker", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ShyLU_Node", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ShyLU_NodeHTS", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ShyLU_NodeFastILU", True))

        if self.spec.satisfies("+hypre"):
            args.append(self.define("TRILINOS_TPL_ENABLE_HYPRE", True))

        if self.spec.satisfies("+cholmod"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Cholmod", True))

        if self.spec.satisfies("+lemon"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Lemon", True))

        if self.spec.satisfies("+metis"):
            args.append(self.define("TRILINOS_TPL_ENABLE_METIS", True))

        if self.spec.satisfies("+mpi"):
            args.append(self.define("TRILINOS_TPL_ENABLE_MPI", True))

        return args
