# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosIfpack2(TrilinosBaseClass):
    """Trilinos Ifpack2 package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on("kokkos-kernels")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-xpetra")
    depends_on_trilinos_package("trilinos-zoltan2core")
    depends_on_trilinos_package("trilinos-thyratpetraadapters")
    depends_on_trilinos_package("trilinos-thyra")
    depends_on_trilinos_package("trilinos-amesos2")
    depends_on_trilinos_package("trilinos-shylu_nodebasker")
    depends_on_trilinos_package("trilinos-shylu_node")
    depends_on_trilinos_package("trilinos-shylu_nodehts")
    depends_on_trilinos_package("trilinos-shylu_nodefastilu")

    # Optional external (TPL) dependencies
    depends_on("hypre")
    depends_on("metis")
    depends_on("mpi")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Ifpack2", True),
        ]
        return args
