# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosROL(TrilinosBaseClass):
    """Trilinos ROL package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-belos")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-thyra")
    depends_on_trilinos_package("trilinos-sacado")
    depends_on_trilinos_package("trilinos-intrepid2")
    depends_on_trilinos_package("trilinos-minitensor")
    depends_on_trilinos_package("trilinos-shards")
    depends_on_trilinos_package("trilinos-amesos2")
    depends_on_trilinos_package("trilinos-ifpack2")
    depends_on_trilinos_package("trilinos-muelu")
    depends_on_trilinos_package("trilinos-tempus")

    # Optional external (TPL) dependencies
    depends_on("boost")
    depends_on("eigen")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_ROL", True),
        ]
        return args
