# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosRol(TrilinosBaseClass):
    """Trilinos ROL package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("boost", default=True, description="Enable boost support")
    variant("arrayfirecpu", default=True, description="Enable arrayfire support")
    variant("eigen", default=True, description="Enable eigen support")


    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-belos")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-thyra")
    depends_on_trilinos_package("trilinos-sacado")
    depends_on_trilinos_package("trilinos-intrepid2")
    depends_on_trilinos_package("trilinos-minitensor")
    depends_on_trilinos_package("trilinos-shards")
    depends_on_trilinos_package("trilinos-amesos2")
    depends_on_trilinos_package("trilinos-ifpack2")
    depends_on_trilinos_package("trilinos-muelu")
    depends_on_trilinos_package("trilinos-tempus")

    # Optional external (TPL) dependencies
    depends_on("boost", when="+boost")
    depends_on("arrayfire", when="+arrayfirecpu")
    depends_on("eigen", when="+eigen")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_ROL", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Belos", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Thyra", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Sacado", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Intrepid2", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_MiniTensor", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Shards", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Amesos2", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Ifpack2", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_MueLu", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Tempus", True))

        if self.spec.satisfies("+boost"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Boost", True))

        if self.spec.satisfies("+arrayfirecpu"):
            args.append(self.define("TRILINOS_TPL_ENABLE_ArrayFireCPU", True))

        if self.spec.satisfies("+eigen"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Eigen", True))

        return args
