# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosStratimikos(TrilinosBaseClass):
    """Trilinos Stratimikos package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-thyracore")
    depends_on_trilinos_package("trilinos-thyra")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-amesos2")
    depends_on_trilinos_package("trilinos-belos")
    depends_on_trilinos_package("trilinos-ifpack2")
    depends_on_trilinos_package("trilinos-thyratpetraadapters")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Stratimikos", True),
        ]
        return args
