# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosPamgen(TrilinosBaseClass):
    """Trilinos Pamgen package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional external (TPL) dependencies
    depends_on("boost")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Pamgen", True),
        ]
        return args
