# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosPamgen(TrilinosBaseClass):
    """Trilinos Pamgen package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("exodusii", default=True, description="Enable exodusii support")
    variant("boost", default=True, description="Enable boost support")


    # Optional external (TPL) dependencies
    depends_on("exodusii", when="+exodusii")
    depends_on("boost", when="+boost")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Pamgen", True))


        if self.spec.satisfies("+exodusii"):
            args.append(self.define("TRILINOS_TPL_ENABLE_ExodusII", True))

        if self.spec.satisfies("+boost"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Boost", True))

        return args
