# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosAmesos2(TrilinosBaseClass):
    """Trilinos Amesos2 package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-trilinosss")
    depends_on("kokkos")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-shylu_nodebasker")
    depends_on_trilinos_package("trilinos-shylu_node")
    depends_on_trilinos_package("trilinos-shylu_nodetacho")

    # Optional external (TPL) dependencies
    depends_on("mpi")
    depends_on("superlu")
    depends_on("superlu-dist")
    depends_on("lapack")
    depends_on("parmetis")
    depends_on("metis")
    depends_on("mumps")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Amesos2", True),
        ]
        return args
