# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosAmesos2(TrilinosBaseClass):
    """Trilinos Amesos2 package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("superlu", default=True, description="Enable superlu support")
    variant("superludist", default=True, description="Enable superlu-dist support")
    variant("lapack", default=True, description="Enable lapack support")
    variant("parmetis", default=True, description="Enable parmetis support")
    variant("metis", default=True, description="Enable metis support")


    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-trilinosss")
    depends_on("kokkos")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-shylu-node +shylu-nodebasker +shylu-nodetacho")

    # Optional external (TPL) dependencies
    depends_on("mpi", when="+mpi")
    depends_on("superlu", when="+superlu")
    depends_on("superlu-dist", when="+superludist")
    depends_on("lapack", when="+lapack")
    depends_on("parmetis", when="+parmetis")
    depends_on("metis", when="+metis")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Amesos2", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_TrilinosSS", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ShyLU_NodeBasker", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ShyLU_Node", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ShyLU_NodeTacho", True))

        if self.spec.satisfies("+mpi"):
            args.append(self.define("TRILINOS_TPL_ENABLE_MPI", True))

        if self.spec.satisfies("+superlu"):
            args.append(self.define("TRILINOS_TPL_ENABLE_SuperLU", True))

        if self.spec.satisfies("+superludist"):
            args.append(self.define("TRILINOS_TPL_ENABLE_SuperLUDist", True))

        if self.spec.satisfies("+lapack"):
            args.append(self.define("TRILINOS_TPL_ENABLE_LAPACK", True))

        if self.spec.satisfies("+parmetis"):
            args.append(self.define("TRILINOS_TPL_ENABLE_ParMETIS", True))

        if self.spec.satisfies("+metis"):
            args.append(self.define("TRILINOS_TPL_ENABLE_METIS", True))

        return args
