# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosShyluNode(TrilinosBaseClass):
    """Trilinos ShyLU_Node package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Subpackage variants
    variant("shylu-nodehts", default=True, description="Enable the ShyLU_NodeHTS subpackage")
    variant("shylu-nodetacho", default=True, description="Enable the ShyLU_NodeTacho subpackage")
    variant("shylu-nodebasker", default=True, description="Enable the ShyLU_NodeBasker subpackage")
    variant("shylu-nodefastilu", default=True, description="Enable the ShyLU_NodeFastILU subpackage")

    # Optional TPL variants
    variant("blas", default=True, description="Enable blas support")
    variant("metis", default=True, description="Enable metis support")
    variant("lapack", default=True, description="Enable lapack support")
    variant("scotch", default=True, description="Enable scotch support")


    # Required package dependencies
    depends_on("kokkos")
    depends_on_trilinos_package("trilinos-trilinosss")
    depends_on_trilinos_package("trilinos-teuchos")

    # Optional package dependencies
    depends_on("kokkos-kernels", when="+shylu-nodehts")

    # Optional external (TPL) dependencies
    depends_on("blas", when="+blas")
    depends_on("metis", when="+metis")
    depends_on("lapack", when="+lapack")
    depends_on("cuda", when="+cuda")
    depends_on("scotch", when="+scotch")

    # TPL conflicts: subpackages that require an optional TPL
    conflicts("~blas", when="+shylu-nodehts")
    conflicts("~blas", when="+shylu-nodetacho")
    conflicts("~metis", when="+shylu-nodetacho")
    conflicts("~metis", when="+shylu-nodebasker")
    conflicts("~lapack", when="+shylu-nodetacho")
    conflicts("~cuda", when="+shylu-nodetacho")
    conflicts("~scotch", when="+shylu-nodebasker")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_ShyLU_Node", True))

        if self.spec.satisfies("+shylu-nodehts"):
            args.append(self.define("Trilinos_ENABLE_ShyLU_NodeHTS", True))

        if self.spec.satisfies("+shylu-nodetacho"):
            args.append(self.define("Trilinos_ENABLE_ShyLU_NodeTacho", True))

        if self.spec.satisfies("+shylu-nodebasker"):
            args.append(self.define("Trilinos_ENABLE_ShyLU_NodeBasker", True))

        if self.spec.satisfies("+shylu-nodefastilu"):
            args.append(self.define("Trilinos_ENABLE_ShyLU_NodeFastILU", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_TrilinosSS", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))

        if self.spec.satisfies("+blas"):
            args.append(self.define("TRILINOS_TPL_ENABLE_BLAS", True))

        if self.spec.satisfies("+metis"):
            args.append(self.define("TRILINOS_TPL_ENABLE_METIS", True))

        if self.spec.satisfies("+lapack"):
            args.append(self.define("TRILINOS_TPL_ENABLE_LAPACK", True))

        if self.spec.satisfies("+cuda"):
            args.append(self.define("TRILINOS_TPL_ENABLE_CUDA", True))

        if self.spec.satisfies("+scotch"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Scotch", True))

        return args
