# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosShyLU_Node(TrilinosBaseClass):
    """Trilinos ShyLU_Node package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Subpackage variants
    variant("shylu-nodehts", default=True, description="Enable the ShyLU_NodeHTS subpackage")
    variant("shylu-nodetacho", default=True, description="Enable the ShyLU_NodeTacho subpackage")
    variant("shylu-nodebasker", default=True, description="Enable the ShyLU_NodeBasker subpackage")
    variant("shylu-nodefastilu", default=True, description="Enable the ShyLU_NodeFastILU subpackage")

    # Required package dependencies
    depends_on("kokkos")
    depends_on_trilinos_package("trilinos-trilinosss")
    depends_on_trilinos_package("trilinos-teuchos")

    # Optional package dependencies
    depends_on("kokkos-kernels", when="+shylu-nodehts")

    # Optional external (TPL) dependencies
    depends_on("blas", when="+shylu-nodehts")
    depends_on("blas", when="+shylu-nodetacho")
    depends_on("metis", when="+shylu-nodetacho")
    depends_on("metis", when="+shylu-nodebasker")
    depends_on("lapack", when="+shylu-nodetacho")
    depends_on("cuda", when="+shylu-nodetacho")
    depends_on("scotch", when="+shylu-nodebasker")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_ShyLU_Node", True),
        ]
        return args
