# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosBelos(TrilinosBaseClass):
    """Trilinos Belos package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-xpetra")
    depends_on_trilinos_package("trilinos-thyra")
    depends_on("kokkos-kernels")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Belos", True),
        ]
        return args
