# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosBelos(TrilinosBaseClass):
    """Trilinos Belos package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-xpetra")
    depends_on_trilinos_package("trilinos-thyra")
    depends_on("kokkos-kernels")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Belos", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Xpetra", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Thyra", True))

        return args
