# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosTempus(TrilinosBaseClass):
    """Trilinos Tempus package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-thyra")
    depends_on_trilinos_package("trilinos-nox")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Tempus", True),
        ]
        return args
