# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosShyluDd(TrilinosBaseClass):
    """Trilinos ShyLU_DD package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Subpackage variants
    variant("shylu-ddfrosch", default=True, description="Enable the ShyLU_DDFROSch subpackage")
    variant("shylu-ddcommon", default=True, description="Enable the ShyLU_DDCommon subpackage")

    # Required package dependencies
    depends_on_trilinos_package("trilinos-amesos2")
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-xpetra")
    depends_on("kokkos")
    depends_on("kokkos-kernels")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-belos", when="+shylu-ddfrosch")
    depends_on_trilinos_package("trilinos-ifpack2", when="+shylu-ddfrosch")
    depends_on_trilinos_package("trilinos-muelu", when="+shylu-ddfrosch")
    depends_on_trilinos_package("trilinos-stratimikos", when="+shylu-ddfrosch")
    depends_on_trilinos_package("trilinos-thyra", when="+shylu-ddfrosch")
    depends_on_trilinos_package("trilinos-zoltan2", when="+shylu-ddfrosch")

    # Required external (TPL) dependencies
    depends_on("mpi")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_ShyLU_DD", True))

        if self.spec.satisfies("+shylu-ddfrosch"):
            args.append(self.define("Trilinos_ENABLE_ShyLU_DDFROSch", True))

        if self.spec.satisfies("+shylu-ddcommon"):
            args.append(self.define("Trilinos_ENABLE_ShyLU_DDCommon", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Amesos2", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Xpetra", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_MPI", True))

        if self.spec.satisfies("+shylu-ddfrosch"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Belos", True))

        if self.spec.satisfies("+shylu-ddfrosch"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Ifpack2", True))

        if self.spec.satisfies("+shylu-ddfrosch"):
            args.append(self.define("TRILINOS_TPL_ENABLE_MueLu", True))

        if self.spec.satisfies("+shylu-ddfrosch"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Stratimikos", True))

        if self.spec.satisfies("+shylu-ddfrosch"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Thyra", True))

        if self.spec.satisfies("+shylu-ddfrosch"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Zoltan2", True))

        return args
