# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosShyLU_DD(TrilinosBaseClass):
    """Trilinos ShyLU_DD package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Subpackage variants
    variant("shylu-ddfrosch", default=True, description="Enable the ShyLU_DDFROSch subpackage")
    variant("shylu-ddcommon", default=True, description="Enable the ShyLU_DDCommon subpackage")

    # Required package dependencies
    depends_on_trilinos_package("trilinos-amesos2")
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-xpetra")
    depends_on("kokkos")
    depends_on("kokkos-kernels")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-belos", when="+shylu-ddfrosch")
    depends_on_trilinos_package("trilinos-ifpack2", when="+shylu-ddfrosch")
    depends_on_trilinos_package("trilinos-muelu", when="+shylu-ddfrosch")
    depends_on_trilinos_package("trilinos-stratimikos", when="+shylu-ddfrosch")
    depends_on_trilinos_package("trilinos-thyra", when="+shylu-ddfrosch")
    depends_on_trilinos_package("trilinos-zoltan2", when="+shylu-ddfrosch")

    # Required external (TPL) dependencies
    depends_on("mpi")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_ShyLU_DD", True),
        ]
        return args
