# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosTrilinosBuildStats(TrilinosBaseClass):
    """Trilinos TrilinosBuildStats package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_TrilinosBuildStats", True))


        return args
