# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosZoltan(TrilinosBaseClass):
    """Trilinos Zoltan package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("metis", default=True, description="Enable metis support")
    variant("parmetis", default=True, description="Enable parmetis support")
    variant("patoh", default=True, description="Enable patoh support")
    variant("scotch", default=True, description="Enable scotch support")
    variant("zlib", default=True, description="Enable zlib-api support")


    # Optional external (TPL) dependencies
    depends_on("mpi", when="+mpi")
    depends_on("metis", when="+metis")
    depends_on("parmetis", when="+parmetis")
    depends_on("patoh", when="+patoh")
    depends_on("scotch", when="+scotch")
    depends_on("zlib-api", when="+zlib")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_Zoltan", True))


        if self.spec.satisfies("+mpi"):
            args.append(self.define("TRILINOS_TPL_ENABLE_MPI", True))

        if self.spec.satisfies("+metis"):
            args.append(self.define("TRILINOS_TPL_ENABLE_METIS", True))

        if self.spec.satisfies("+parmetis"):
            args.append(self.define("TRILINOS_TPL_ENABLE_ParMETIS", True))

        if self.spec.satisfies("+patoh"):
            args.append(self.define("TRILINOS_TPL_ENABLE_PaToH", True))

        if self.spec.satisfies("+scotch"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Scotch", True))

        if self.spec.satisfies("+zlib"):
            args.append(self.define("TRILINOS_TPL_ENABLE_Zlib", True))

        return args
