# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosZoltan(TrilinosBaseClass):
    """Trilinos Zoltan package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional external (TPL) dependencies
    depends_on("mpi")
    depends_on("metis")
    depends_on("parmetis")
    depends_on("scotch")
    depends_on("zlib-api")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Zoltan", True),
        ]
        return args
