# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosMiniTensor(TrilinosBaseClass):
    """Trilinos MiniTensor package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos +teuchoscore")
    depends_on("kokkos")
    depends_on("kokkos-kernels")
    depends_on_trilinos_package("trilinos-sacado")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_MiniTensor", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_TeuchosCore", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))
        args.append(self.define("TRILINOS_TPL_ENABLE_Sacado", True))

        return args
