# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosXpetra(TrilinosBaseClass):
    """Trilinos Xpetra package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on("kokkos")
    depends_on("kokkos-kernels")
    depends_on_trilinos_package("trilinos-tpetra")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-thyra")

    # Required external (TPL) dependencies
    depends_on("blas")
    depends_on("lapack")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_Xpetra", True),
        ]
        return args
