# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosNOX(TrilinosBaseClass):
    """Trilinos NOX package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-thyracore")
    depends_on_trilinos_package("trilinos-thyra")
    depends_on_trilinos_package("trilinos-belos")
    depends_on_trilinos_package("trilinos-anasazi")
    depends_on_trilinos_package("trilinos-stratimikos")
    depends_on_trilinos_package("trilinos-teko")
    depends_on_trilinos_package("trilinos-tpetra")

    # Optional external (TPL) dependencies
    depends_on("lapack")
    depends_on("blas")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_NOX", True),
        ]
        return args
