# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

import os
import pathlib
import re
import sys
from spack.package import *
from ..trilinos_base_class.package import TrilinosBaseClass
from ..trilinos_base_class.package import depends_on_trilinos_package
from ..trilinos_base_class.package import trilinos_variant
from ..trilinos_base_class.package import list_of_trilinos_variants


class TrilinosNox(TrilinosBaseClass):
    """Trilinos NOX package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Optional TPL variants
    variant("petsc", default=True, description="Enable petsc support")
    variant("lapack", default=True, description="Enable lapack support")
    variant("blas", default=True, description="Enable blas support")


    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-thyra +thyracore")
    depends_on_trilinos_package("trilinos-belos")
    depends_on_trilinos_package("trilinos-anasazi")
    depends_on_trilinos_package("trilinos-stratimikos")
    depends_on_trilinos_package("trilinos-teko")
    depends_on_trilinos_package("trilinos-tpetra")

    # Optional external (TPL) dependencies
    depends_on("petsc", when="+petsc")
    depends_on("lapack", when="+lapack")
    depends_on("blas", when="+blas")

    def cmake_args(self):
        args = super().cmake_args()
        args.append(self.define("Trilinos_ENABLE_NOX", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Teuchos", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_ThyraCore", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Thyra", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Belos", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Anasazi", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Stratimikos", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Teko", True))

        args.append(self.define("TRILINOS_TPL_ENABLE_Tpetra", True))

        if self.spec.satisfies("+petsc"):
            args.append(self.define("TRILINOS_TPL_ENABLE_PETSC", True))

        if self.spec.satisfies("+lapack"):
            args.append(self.define("TRILINOS_TPL_ENABLE_LAPACK", True))

        if self.spec.satisfies("+blas"):
            args.append(self.define("TRILINOS_TPL_ENABLE_BLAS", True))

        return args
