# Copyright Spack Project Developers. See COPYRIGHT file for details.
# Auto-generated by generate_spack_packages.py
# Source: TrilinosPackageDependencies.xml

from spack.package import *


class TrilinosPyTrilinos2(TrilinosBaseClass):
    """Trilinos PyTrilinos2 package.

    Part of the Trilinos Project (https://trilinos.github.io).
    """

    # Required package dependencies
    depends_on_trilinos_package("trilinos-teuchos")
    depends_on_trilinos_package("trilinos-tpetra")
    depends_on_trilinos_package("trilinos-thyra")
    depends_on_trilinos_package("trilinos-thyratpetraadapters")
    depends_on_trilinos_package("trilinos-stratimikos")

    # Optional package dependencies
    depends_on_trilinos_package("trilinos-muelu")

    def cmake_args(self):
        args = [
            self.define("Trilinos_ENABLE_PyTrilinos2", True),
        ]
        return args
